controllers:
    resource: ../../src/Controller/
    type: annotation
participant:
    resource: App\Controller\ParticipantController
    type: rest
city:
    resource: App\Controller\CityController
    type: rest

